server:
  port: 8080

spring:
  application:
    name: surname
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:13306/surname
    username: surname_ygq
    password: Test123
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

mybatis:
  mapper-locations: com/surname/mapper/*.xml  # 指定mapper.xml配置文件的位置
  configuration:
    map-underscore-to-camel-case: true  # 开启下划线转驼峰命名


token:
  secret: surname888  #密钥规则
  expireTime: 30  #过期时间（分钟）
